// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// as_tibblex
Rcpp::DataFrame as_tibblex(Rcpp::DataFrame& df);
RcppExport SEXP _Rapi_as_tibblex(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(as_tibblex(df));
    return rcpp_result_gen;
END_RCPP
}
// lag_df_c
Rcpp::DataFrame lag_df_c(Rcpp::DataFrame& df2, const Rcpp::List& lag_list);
RcppExport SEXP _Rapi_lag_df_c(SEXP df2SEXP, SEXP lag_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type df2(df2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lag_list(lag_listSEXP);
    rcpp_result_gen = Rcpp::wrap(lag_df_c(df2, lag_list));
    return rcpp_result_gen;
END_RCPP
}
// lag_df2_c
Rcpp::DataFrame lag_df2_c(Rcpp::DataFrame& df2, const Rcpp::List& lag_list);
RcppExport SEXP _Rapi_lag_df2_c(SEXP df2SEXP, SEXP lag_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type df2(df2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lag_list(lag_listSEXP);
    rcpp_result_gen = Rcpp::wrap(lag_df2_c(df2, lag_list));
    return rcpp_result_gen;
END_RCPP
}
// remove_column_cpp
Rcpp::DataFrame remove_column_cpp(Rcpp::DataFrame& df, std::string column);
RcppExport SEXP _Rapi_remove_column_cpp(SEXP dfSEXP, SEXP columnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type column(columnSEXP);
    rcpp_result_gen = Rcpp::wrap(remove_column_cpp(df, column));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rapi_as_tibblex", (DL_FUNC) &_Rapi_as_tibblex, 1},
    {"_Rapi_lag_df_c", (DL_FUNC) &_Rapi_lag_df_c, 2},
    {"_Rapi_lag_df2_c", (DL_FUNC) &_Rapi_lag_df2_c, 2},
    {"_Rapi_remove_column_cpp", (DL_FUNC) &_Rapi_remove_column_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rapi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
