# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_tibblex <- function(df) {
  .Call(`_Rapi_as_tibblex`, df)
}

lag_df_c <- function(df2, lag_list) {
  .Call(`_Rapi_lag_df_c`, df2, lag_list)
}

lag_df2_c <- function(df2, lag_list) {
  .Call(`_Rapi_lag_df2_c`, df2, lag_list)
}

remove_column_cpp <- function(df, column) {
  .Call(`_Rapi_remove_column_cpp`, df, column)
}
